server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/paopaoping/_76/config.git
          search-paths: config
          username: 331099716@qq.com
          passphrase: kira0769
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/